"""create initial tables

Revision ID: 33eed5ed267d
Revises: 
Create Date: 2025-04-26 19:24:47.810720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eed5ed267d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=True),
    sa.Column('predicted_direction', sa.String(), nullable=True),
    sa.Column('actual_direction', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_results_prediction_date'), 'backtest_results', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_backtest_results_symbol'), 'backtest_results', ['symbol'], unique=False)
    op.create_table('bhavcopies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('deliverable_qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bhavcopies_date'), 'bhavcopies', ['date'], unique=False)
    op.create_index(op.f('ix_bhavcopies_id'), 'bhavcopies', ['id'], unique=False)
    op.create_index(op.f('ix_bhavcopies_symbol'), 'bhavcopies', ['symbol'], unique=False)
    op.create_table('predictions_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('predicted_for_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_daily_date'), 'predictions_daily', ['date'], unique=False)
    op.create_index(op.f('ix_predictions_daily_id'), 'predictions_daily', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_daily_predicted_for_date'), 'predictions_daily', ['predicted_for_date'], unique=False)
    op.create_index(op.f('ix_predictions_daily_symbol'), 'predictions_daily', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_daily_symbol'), table_name='predictions_daily')
    op.drop_index(op.f('ix_predictions_daily_predicted_for_date'), table_name='predictions_daily')
    op.drop_index(op.f('ix_predictions_daily_id'), table_name='predictions_daily')
    op.drop_index(op.f('ix_predictions_daily_date'), table_name='predictions_daily')
    op.drop_table('predictions_daily')
    op.drop_index(op.f('ix_bhavcopies_symbol'), table_name='bhavcopies')
    op.drop_index(op.f('ix_bhavcopies_id'), table_name='bhavcopies')
    op.drop_index(op.f('ix_bhavcopies_date'), table_name='bhavcopies')
    op.drop_table('bhavcopies')
    op.drop_index(op.f('ix_backtest_results_symbol'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_prediction_date'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
